In [1]:
import pandas as pd
print(pd.__version__)

0.23.0

In [2]:
# Reading values from csv
exam_data=pd.read_csv('C:/Users/chait/Desktop/Machine Learning/Datasets/exams.csv',quotechar='"')
exam_data

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,male,group C,high school,standard,completed,87,83,84
1,female,group A,associate's degree,standard,none,58,75,72
2,female,group C,high school,standard,none,76,73,80
3,female,group B,some college,standard,none,56,68,68
4,male,group E,some high school,free/reduced,completed,87,84,82
5,female,group D,bachelor's degree,standard,none,64,75,78
6,male,group C,some college,standard,completed,76,84,84
7,male,group C,master's degree,standard,none,85,69,69
8,female,group D,bachelor's degree,free/reduced,none,58,72,71
9,female,group C,some college,standard,none,59,66,63
10,male,group B,some high school,standard,completed,61,67,63
11,male,group A,some college,free/reduced,none,55,55,54
12,female,group D,associate's degree,free/reduced,none,67,76,76
13,female,group B,master's degree,standard,completed,83,90,94
14,male,group D,some college,standard,none,74,65,62
15,male,group A,some high school,standard,completed,80,73,72
16,female,group E,some college,free/reduced,none,59,59,64
17,male,group C,associate's degree,standard,none,59,52,55
18,male,group D,associate's degree,standard,completed,81,79,83
19,male,group B,master's degree,standard,none,56,61,55
20,female,group C,high school,standard,none,78,88,79
21,male,group B,bachelor's degree,standard,completed,64,61,63
22,female,group C,some college,free/reduced,completed,44,55,54
23,male,group E,some college,standard,none,79,69,56
24,female,group B,high school,standard,completed,72,84,85
25,male,group C,associate's degree,free/reduced,none,45,54,48
26,male,group C,associate's degree,standard,completed,86,89,82
27,female,group A,associate's degree,free/reduced,completed,61,84,82
28,male,group C,associate's degree,standard,completed,64,74,72
29,male,group B,high school,free/reduced,completed,59,61,60
...,...,...,...,...,...,...,...,...
970,male,group D,some college,free/reduced,completed,32,41,41
971,male,group A,master's degree,standard,none,68,62,62
972,male,group D,associate's degree,standard,completed,65,74,74
973,female,group C,bachelor's degree,standard,none,93,97,95
974,male,group D,high school,standard,completed,69,77,76
975,male,group B,associate's degree,standard,none,71,66,60
976,male,group A,associate's degree,standard,none,87,84,80
977,male,group B,associate's degree,standard,completed,90,70,76
978,female,group C,associate's degree,standard,completed,56,80,81
979,female,group D,some college,standard,none,58,75,72
980,female,group D,some high school,standard,none,62,75,76
981,male,group D,some college,standard,completed,92,91,100
982,female,group B,bachelor's degree,standard,none,73,76,80
983,male,group B,associate's degree,standard,completed,77,63,63
984,female,group C,some high school,free/reduced,none,41,72,64
985,male,group D,some high school,standard,completed,79,68,69
986,female,group D,some college,standard,none,39,49,47
987,female,group B,high school,standard,completed,55,72,64
988,male,group B,bachelor's degree,free/reduced,completed,79,77,74
989,male,group B,some college,standard,completed,68,64,68
990,female,group C,high school,standard,completed,46,41,50
991,female,group B,some college,free/reduced,completed,60,81,79
992,female,group C,associate's degree,free/reduced,none,48,63,52
993,male,group C,some college,standard,completed,70,73,78
994,female,group B,some high school,free/reduced,completed,53,63,65
995,male,group E,some high school,standard,completed,66,59,59
996,female,group C,high school,standard,none,78,97,91
997,male,group E,some high school,free/reduced,none,71,71,67
998,male,group B,some college,standard,completed,66,62,61
999,male,group B,some high school,standard,none,42,37,38

In [3]:
# Calculating average for each column
math_avg=exam_data['math score'].mean()
reading_avg = exam_data['reading score'].mean()
writing_avg= exam_data['writing score'].mean()
print('Math Avg-->',math_avg,'\nReading Avg-->',reading_avg,'\nwriting_avg-->',writing_avg)

Math Avg--> 66.84
Reading Avg--> 69.647
writing_avg--> 68.739

In [4]:
# Standard normalization for numerical data
from sklearn import preprocessing
exam_data['math score'] = preprocessing.scale(exam_data['math score'])
exam_data['reading score'] = preprocessing.scale(exam_data['reading score'])
exam_data['writing score'] = preprocessing.scale(exam_data['writing score'])

C:\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by the scale function.
  warnings.warn(msg, DataConversionWarning)

In [8]:
# Label Encoding for Categorical data using sklearn
LE=preprocessing.LabelEncoder()
exam_data['gender'] = LE.fit_transform(exam_data['gender'].astype(str))

In [9]:
# Label Encoding for Categorical data using pandas
exam_data = pd.get_dummies(exam_data,columns=['gender'])
exam_data

,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,gender_0,gender_1
0,group C,high school,standard,completed,1.321462,0.899245,0.988574,0,1
1,group A,associate's degree,standard,none,-0.579451,0.360493,0.211240,1,0
2,group C,high school,standard,none,0.600426,0.225805,0.729463,1,0
3,group B,some college,standard,none,-0.710548,-0.110916,-0.047871,1,0
4,group E,some high school,free/reduced,completed,1.321462,0.966589,0.859019,0,1
5,group D,bachelor's degree,standard,none,-0.186158,0.360493,0.599907,1,0
6,group C,some college,standard,completed,0.600426,0.966589,0.988574,0,1
7,group C,master's degree,standard,none,1.190364,-0.043572,0.016907,0,1
8,group D,bachelor's degree,free/reduced,none,-0.579451,0.158461,0.146463,1,0
9,group C,some college,standard,none,-0.513902,-0.245604,-0.371760,1,0
10,group B,some high school,standard,completed,-0.382804,-0.178260,-0.371760,0,1
11,group A,some college,free/reduced,none,-0.776097,-0.986388,-0.954760,0,1
12,group D,associate's degree,free/reduced,none,0.010488,0.427837,0.470352,1,0
13,group B,master's degree,standard,completed,1.059267,1.370654,1.636352,1,0
14,group D,some college,standard,none,0.469329,-0.312948,-0.436538,0,1
15,group A,some high school,standard,completed,0.862621,0.225805,0.211240,0,1
16,group E,some college,free/reduced,none,-0.513902,-0.717012,-0.306982,1,0
17,group C,associate's degree,standard,none,-0.513902,-1.188421,-0.889982,0,1
18,group D,associate's degree,standard,completed,0.928170,0.629869,0.923796,0,1
19,group B,master's degree,standard,none,-0.710548,-0.582324,-0.889982,0,1
20,group C,high school,standard,none,0.731524,1.235965,0.664685,1,0
21,group B,bachelor's degree,standard,completed,-0.186158,-0.582324,-0.371760,0,1
22,group C,some college,free/reduced,completed,-1.497132,-0.986388,-0.954760,1,0
23,group E,some college,standard,none,0.797072,-0.043572,-0.825204,0,1
24,group B,high school,standard,completed,0.338231,0.966589,1.053352,1,0
25,group C,associate's degree,free/reduced,none,-1.431584,-1.053732,-1.343427,0,1
26,group C,associate's degree,standard,completed,1.255913,1.303309,0.859019,0,1
27,group A,associate's degree,free/reduced,completed,-0.382804,0.966589,0.859019,1,0
28,group C,associate's degree,standard,completed,-0.186158,0.293149,0.211240,0,1
29,group B,high school,free/reduced,completed,-0.513902,-0.582324,-0.566093,0,1
...,...,...,...,...,...,...,...,...,...
970,group D,some college,free/reduced,completed,-2.283717,-1.929205,-1.796872,0,1
971,group A,master's degree,standard,none,0.076036,-0.514980,-0.436538,0,1
972,group D,associate's degree,standard,completed,-0.120610,0.293149,0.340796,0,1
973,group C,bachelor's degree,standard,none,1.714754,1.842062,1.701130,1,0
974,group D,high school,standard,completed,0.141585,0.495181,0.470352,0,1
975,group B,associate's degree,standard,none,0.272683,-0.245604,-0.566093,0,1
976,group A,associate's degree,standard,none,1.321462,0.966589,0.729463,0,1
977,group B,associate's degree,standard,completed,1.518108,0.023772,0.470352,0,1
978,group C,associate's degree,standard,completed,-0.710548,0.697213,0.794241,1,0
979,group D,some college,standard,none,-0.579451,0.360493,0.211240,1,0
980,group D,some high school,standard,none,-0.317256,0.360493,0.470352,1,0
981,group D,some college,standard,completed,1.649205,1.437998,2.025019,0,1
982,group B,bachelor's degree,standard,none,0.403780,0.427837,0.729463,1,0
983,group B,associate's degree,standard,completed,0.665975,-0.447636,-0.371760,0,1
984,group C,some high school,free/reduced,none,-1.693779,0.158461,-0.306982,1,0
985,group D,some high school,standard,completed,0.797072,-0.110916,0.016907,0,1
986,group D,some college,standard,none,-1.824876,-1.390453,-1.408205,1,0
987,group B,high school,standard,completed,-0.776097,0.158461,-0.306982,1,0
988,group B,bachelor's degree,free/reduced,completed,0.797072,0.495181,0.340796,0,1
989,group B,some college,standard,completed,0.076036,-0.380292,-0.047871,0,1
990,group C,high school,standard,completed,-1.366035,-1.929205,-1.213871,1,0
991,group B,some college,free/reduced,completed,-0.448353,0.764557,0.664685,1,0
992,group C,associate's degree,free/reduced,none,-1.234938,-0.447636,-1.084316,1,0
993,group C,some college,standard,completed,0.207134,0.225805,0.599907,0,1
994,group B,some high school,free/reduced,completed,-0.907194,-0.447636,-0.242204,1,0
995,group E,some high school,standard,completed,-0.055061,-0.717012,-0.630871,0,1
996,group C,high school,standard,none,0.731524,1.842062,1.442019,1,0
997,group E,some high school,free/reduced,none,0.272683,0.091117,-0.112649,0,1
998,group B,some college,standard,completed,-0.055061,-0.514980,-0.501315,0,1
999,group B,some high school,standard,none,-1.628230,-2.198581,-1.991205,0,1